version: '3.9'
services:
  backend-stub:
    image: dzx912/ping-pong-grpc-stub:1
    networks:
      - backend

  front:
    image: dzx912/simple-ping-pong-server-native:1
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./configuration/application.yaml:/work/config/application.yaml
    depends_on:
      - backend-stub

networks:
  backend: