front:
  name: "ping-pong-front"
  port_inside: 8080
  replicaCount: 2
  image:
    repository: dzx912/simple-ping-pong-server
    pullPolicy: IfNotPresent
    tag: "1"
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  probe:
    initialDelaySeconds: 5
    timeoutSeconds: 1
    periodSeconds: 1
    failureThreshold: 3
  selectorLabels:
    app:
      kubernetes:
        io/name: ping-pong-front

back:
  name: "ping-pong-back"
  replicaCount: 1
  image:
    repository: dzx912/ping-pong-grpc-stub
    pullPolicy: IfNotPresent
    tag: "1"
  delay:
    low: 5000
    upper: 10000
  port_inside: 8080
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 500m
      memory: 256Mi
  selectorLabels:
    app:
      kubernetes:
        io/name: ping-pong-back

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: HOST_APP
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
