kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.frontJit.name }}-config
data:
  application.yaml: |
    quarkus:
      http:
        port: {{ .Values.frontJit.port_inside }}
      grpc:
        clients:
          pingPong:
            host: {{ .Values.back.name }}.{{ .Release.Namespace }}.svc.cluster.local
