kind: Deployment
apiVersion: apps/v1
metadata:
  name: ping-pong-front-jit
  labels:
    {{- include "ping-pong.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontJit.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: ping-pong-front-jit
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ping-pong-front-jit
    spec:
      containers:
        - name: ping-pong-front-jit-cont
          image: "{{ .Values.frontJit.image.repository }}:{{ .Values.frontJit.image.tag }}"
          imagePullPolicy: {{ .Values.frontJit.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontJit.port_inside }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: http
            initialDelaySeconds: {{ .Values.frontJit.probe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.frontJit.probe.timeoutSeconds }}
            periodSeconds: {{ .Values.frontJit.probe.periodSeconds }}
            failureThreshold: {{ .Values.frontJit.probe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: http
            initialDelaySeconds: {{ .Values.frontJit.probe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.frontJit.probe.timeoutSeconds }}
            periodSeconds: {{ .Values.frontJit.probe.periodSeconds }}
            failureThreshold: {{ .Values.frontJit.probe.failureThreshold }}
          resources:
            {{- toYaml .Values.frontJit.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.frontJit.name }}-config-volume
              mountPath: /work/config/
      volumes:
        - name: {{ .Values.frontJit.name }}-config-volume
          configMap:
            name: {{ .Values.frontJit.name }}-config