kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ .Values.front.name | trunc 63 | quote }}
spec:
  host: >-
    pp-f-{{ .Release.Namespace }}.apps.lt-gen2.ocp.delta.sbrf.ru
  to:
    kind: Service
    name: {{ .Values.front.name }}
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None