kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.back.name }}
  labels:
    {{- include "ping-pong.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: grpc
      port: 9000
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: ping-pong-back
